### ISSUE TITLE
static site generation & dat publishing

### ISSUE THREAD

**Issue by whoisgina** [datproject/dat-foundation-website#54]
Can someone write a task that publishes changes to dat when the site is built?

**Comment by RangerMauve** [comment]
CC @sammacbeth - Were you still interested in tackling this?

**Comment by sammacbeth** [comment]
It's on my radar. What is the preferred method? Should it be integrated with Netlify or can we use Github Actions?

**Comment by okdistribute** [comment]
Awesome! @sammacbeth in the past we've used Netlify but that was before GitHub Actions were a Thing(tm). I'd say whatever is most comfortable for you, since this is all volunteer anyway.

**Comment by RangerMauve** [comment]
Added Sam to the collaborators. Lemme know if you need a higher level of permissions to mess with it. 💜

**Comment by okdistribute** [comment]
this is done!
